#edituser:
 # path: /edituser/{id}
  #defaults: { _controller: /Controller/RegistrationController::editUserAction }
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#deleteUser:
#  path: /deleteUser/{id}
#  defaults: { _controller: src/Controller/RegistrationController::removeUserAction, id: null }